# Generated by Django 3.2.8 on 2022-01-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_fooditem_name'),
        ('orders', '0002_alter_orderdetails_fooditemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='foodItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.fooditem'),
        ),
    ]
