# Generated by Django 3.2.8 on 2022-01-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdetails_fooditemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderflags',
            name='completed',
        ),
    ]
