# Generated by Django 3.2.8 on 2022-01-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_fooditem_name'),
        ('orders', '0006_remove_orderflags_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='OrderFlags',
            new_name='OrderFlag',
        ),
    ]
