# Generated by Django 3.2.8 on 2021-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bf', 'breakfast'), ('lu', 'lunch'), ('veg', 'vegeterian'), ('nveg', 'non-vegeterian'), ('sn', 'snacks')], max_length=5)),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
