# Generated by Django 3.2.8 on 2021-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20211203_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['category'], 'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name'], 'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Item'},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(related_name='items', to='menu.FoodCategory'),
        ),
    ]
