# Generated by Django 3.2.8 on 2021-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20211203_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Items'},
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='category',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
