# Generated by Django 3.2.8 on 2022-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_fooditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='menu_order',
            field=models.IntegerField(default=None),
        ),
    ]
