# Generated by Django 3.2.8 on 2022-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_foodcategory_menu_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='menu_order',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
