# Generated by Django 3.2.8 on 2022-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20220110_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
