# Generated by Django 3.2.8 on 2022-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_foodcategory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='order',
        ),
    ]
