# Generated by Django 3.2.8 on 2022-01-10 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_rename_order_foodcategory_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='menu_order',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
