# Generated by Django 3.2.8 on 2021-11-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211101_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'ingredient'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Item'},
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=None, upload_to='./images'),
        ),
    ]
