# Generated by Django 3.2.8 on 2021-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
