# Generated by Django 3.2.8 on 2021-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='label',
            field=models.CharField(choices=[], default=None, max_length=20),
        ),
    ]
