# Generated by Django 3.2.8 on 2021-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_fooditem_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(related_name='foodItems', to='menu.FoodCategory'),
        ),
    ]
