# Generated by Django 3.2.8 on 2022-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_foodcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
