# Generated by Django 3.2.8 on 2022-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_remove_foodcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
