# Generated by Django 3.2.8 on 2022-01-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0017_alter_fooditem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableId', models.CharField(max_length=2)),
                ('pending', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('foodItemId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderflags')),
            ],
        ),
    ]
